- hosts: localhost
  tasks:
  - name: install homebrew packages
    tags: [pkgs]
    homebrew:
      name:
        - go
        - bash
        - stow
        - direnv
        - fasd
        - ripgrep
        - graphviz
        - protobuf
        - gh
        - cloc
        - fzf
        - saulpw/vd/visidata
        - noti
  - name: install go packages
    tags: [gopkgs]
    command: go install "{{ item }}"
    with_items:
      - golang.org/x/review/git-codereview@latest
      - golang.org/x/perf/cmd/benchstat@latest
      - github.com/go-delve/delve/cmd/dlv@latest

  - name: get bash path
    tags: [shell]
    command: which bash
    register: bash_path
  - name: register shell
    tags: [shell]
    become: true
    lineinfile:
      path: /etc/shells
      line: "{{ bash_path.stdout }}"
  - name: change default shell
    tags: [shell]
    become: true
    command: chsh -s "{{ bash_path.stdout }}"
  - name: enable touch id in terminal

    tags: [touchid]
    become: true
    lineinfile:
      path: /etc/pam.d/sudo
      line: auth sufficient pam_tid.so
      insertafter: '^#'
      firstmatch: true
