- hosts: localhost
  tasks:
  - name: Install packages
    homebrew:
      name:
        - go
        - bash
        - stow
        - direnv
        - fasd
        - ripgrep
        - graphviz
        - protobuf
        - gh
        - cloc
        - fzf
  - name: get bash path
    command: which bash
    register: bash_path
  - name: register shell
    become: true
    lineinfile:
      path: /etc/shells
      line: "{{ bash_path.stdout }}"
  - name: change default shell
    become: true
    command: chsh -s "{{ bash_path.stdout }}"
  - name: install go packages
    command: go install "{{ item }}"
    with_items:
      - golang.org/x/review/git-codereview@latest
      - golang.org/x/perf/cmd/benchstat@latest

