[ui.theme]
light = "custom-light"
dark = "custom-light"

[[actions]]
name = "show-diff"
lua = '''
jj_interactive("show", context.change_id())
'''

[[bindings]]
action = "show-diff"
seq = ["\\", "d"]
scope = "revisions"
desc = "Show interactive diff"

[[actions]]
name = "edit-file-at"
lua = '''
exec_shell("cursor " .. context.file())
'''

[[bindings]]
action = "edit-file-at"
seq = ["\\", "e"]
scope = "revisions.details"
desc = "Edit file in @"

[[actions]]
name = "edit-file-in-change"
lua = '''
local cid = context.change_id()
local f = context.file()
exec_shell("jj edit '" .. cid .. "' && cursor '" .. f .. "'")
'''

[[bindings]]
action = "edit-file-in-change"
seq = ["\\", "E"]
scope = "revisions.details"
desc = "Edit file in change"

[[actions]]
name = "open-pr"
lua = '''
jj_interactive("pr", context.change_id())
'''

[[bindings]]
action = "open-pr"
seq = ["\\", "p"]
scope = "revisions"
desc = "Open PR"
